name: Master-Deploy

on:
    push:
        branches:
            - master

jobs:
    SSH-Connexion:
        
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v2

            - name: SSH connection
              uses: appleboy/ssh-action@master
              with:
                username: root
                ssh_private_key: ${{ secrets.PROD_SSH_KEY }}
                port: 22
                script: |
                    cd /home/pokemon/
                    ls -la
            - run: ls -la
