name: Master-Deploy

on:
    push:
        branches: [ dev ]

jobs:
    SSH-Connexion:
        
        runs-on: ubuntu-latest
        
        steps:
            - name: Repository checkout
              uses: actions/checkout@v2

            - name: SSH connection
              uses: appleboy/ssh-action@v0.1.4
              with:
                host: "pokeshop.tk"
                username: ${{ secrets.PROD_USER }}
                key: ${{ secrets.PROD_SSH_KEY }}
                port: ${{ secrets.PROD_PORT }}
                script: |
                    cd /home/pokemon
                    mkdir test
